name: UKHO.ConfigurableStub_$(Date:yyyy)$(DayOfYear).$(Rev:.r)

resources:
- repo: self
  clean: true

trigger:
  branches:
    include:
      - refs/heads/*

queue:
  name: NautilusBuild

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
- script: dotnet pack  --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'Drop'